### ISSUE TITLE
[Method] `swapExactETHForTokensSupportingFeeOnTransferTokens`

### ISSUE THREAD

**Issue by AdamB2023** [tsarbuig/WalletHunter#8]
This TX wasn't copied due to method isn't handled?
https://etherscan.io/tx/0x957d9eae404088ad5fce929e0973bd038948d0e26afa961ab8517353d5e38f10

**Comment by tsarbuig** [comment]
it's because he's not interacting with regular Uniswap Router address 

![image](https://user-images.githubusercontent.com/70858574/216713249-bf343893-d152-412c-a43d-f422ab9ec56e.png)


this protection is made you avoid you sniping on wrong website, if another DEX implement same method : bot would try to swap on Uniswap while liquidity is on another bot

--> I'll add this contract to router whitelist

**Comment by tsarbuig** [comment]
v0.49.1g
